media: 
  - label: Images
    name: images
    input: assets/media
    output: assets/media
    categories: [ image ]

content: 
  - name: docs
    label: Documentation
    type: collection
    path: docs
    view:
      fields: [ title, published, date, image ]
    fields:
      - name: published
        label: Published
        type: boolean
        default: true
      - name: date
        label: Date
        type: date
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: markdown
      - name: image
        label: Image
        type: image