media: 
  - label: Images
    name: images
    input: assets/media
    output: assets/media
    categories: [ image ]

content: 
  - name: docs
    label: Documentation
    type: collection
    path: docs
    view:
      fields: [ title, content, image ]
    fields:
      - name: title
        label: Title
        type: string
      - name: content
        label: Content
        type: rich-text
      - name: image
        label: Image
        type: image